### PR TITLE
Added ctrl+left and ctrl_right word jumping for terminal.

### PR DESCRIPTION
**Pull request by harvastum**

### CODE REVIEW

**Comment by smcpeak** [comment]
The intent of the `default-keys-windows` extension is to provide exactly the default key bindings as they appear on Windows (with no extensions active).  In the latest VSCode release (1.70.2), I do not see bindings like the ones you are proposing to add when I ask VSCode for the defaults (command "Preference: Open Default Keyboard Shortcuts (JSON)").  Where do these bindings come from?

**Comment by harvastum** [comment]
This is a system-wide thing in Windows.

**Comment by smcpeak** [comment]
I see that ctrl+left/right move left/right by words in the VSCode Terminal on Windows, but for me (using VSCode-1.70.2) they also that on Linux.  Which OS and VSCode version are you using that needs these additional VSCode bindings?

**Comment by harvastum** [comment]
MacOS

**Comment by smcpeak** [comment]
I see, thanks for the clarification.

The main issue for me is I don't want to deal with the hassle of maintaining an additional custom modification on top of the defaults that I can easily export and copy into `package.json`.  Furthermore, I don't have an easy way to test on Mac, so a feature whose only effect is on that platform is undesirable.

However, I understand that if someone wants the "Windows defaults", they probably have the expectation that ctrl-left/right will work in Terminal.  So, I propose to add something to `README.md` that either explains what to add or links to an extension that adds the bindings; the latter seems preferable.  Would you be willing to make and publish a tiny extension that adds the desired bindings so I could link to that?

**Comment by smcpeak** [comment]
In 4b3d8fe9e2 (which is part of just released 0.0.10) I have added instructions to README.md that I hope will suffice, so closing this PR.

**Pull request closed without merging**
